# Generated by Django 4.2.1 on 2023-07-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_runner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
