# Generated by Django 4.2.1 on 2023-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_relationship_base_relati_from_us_ec4811_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_user', 'to_user'], name='base_relati_from_us_ec4811_idx'),
        ),
    ]
